In [1]:
import pandas as pd

In [4]:
df=pd.read_csv("C:/nan mudhalvan/machine_data.csv")
df

,vendor,model,cycle_time,min_memory,max_memory,cache,min_threads,max_threads,score
0,adviser,32/60,125,256,6000,256,16,128,198
1,amdahl,470v/7,29,8000,32000,32,8,32,269
2,amdahl,470v/7a,29,8000,32000,32,8,32,220
3,amdahl,470v/7b,29,8000,32000,32,8,32,172
4,amdahl,470v/7c,29,8000,16000,32,8,16,132
...,...,...,...,...,...,...,...,...,...
204,sperry,80/8,124,1000,8000,0,1,8,42
205,sperry,90/80-model-3,98,1000,8000,32,2,8,46
206,sratus,32,125,2000,8000,0,2,14,52
207,wang,vs-100,480,512,8000,32,0,0,67
208,wang,vs-90,480,1000,4000,0,0,0,45

### Encode the categorical column – ‘vendor’ using label encoder

In [6]:
# Import label encoder 
from sklearn import preprocessing 

# label_encoder object knows 
# how to understand word labels. 
label_encoder = preprocessing.LabelEncoder() 

# Encode labels in column 'species'. 
df['vendor']= label_encoder.fit_transform(df['vendor']) 
df

,vendor,model,cycle_time,min_memory,max_memory,cache,min_threads,max_threads,score
0,0,32/60,125,256,6000,256,16,128,198
1,1,470v/7,29,8000,32000,32,8,32,269
2,1,470v/7a,29,8000,32000,32,8,32,220
3,1,470v/7b,29,8000,32000,32,8,32,172
4,1,470v/7c,29,8000,16000,32,8,16,132
...,...,...,...,...,...,...,...,...,...
204,27,80/8,124,1000,8000,0,1,8,42
205,27,90/80-model-3,98,1000,8000,32,2,8,46
206,28,32,125,2000,8000,0,2,14,52
207,29,vs-100,480,512,8000,32,0,0,67
208,29,vs-90,480,1000,4000,0,0,0,45

### b.	Identify the vendors who have manufactured less than 5 CPUs and drop those rows from the given dataset, corresponding to the identified vendors.

In [10]:
import pandas as pd

# Assuming your DataFrame is named 'cpu_data' and the column containing vendors is named 'Vendor'

# Grouping by Vendor and counting the number of CPUs each vendor has manufactured
vendor_counts = df['vendor'].value_counts()

# Filtering vendors with less than 5 CPUs
vendors_to_drop = vendor_counts[vendor_counts < 5].index

# Filtering the DataFrame to drop the rows corresponding to these vendors
filtered_df = df[~df['vendor'].isin(vendors_to_drop)]

In [11]:
filtered_df

,vendor,model,cycle_time,min_memory,max_memory,cache,min_threads,max_threads,score
1,1,470v/7,29,8000,32000,32,8,32,269
2,1,470v/7a,29,8000,32000,32,8,32,220
3,1,470v/7b,29,8000,32000,32,8,32,172
4,1,470v/7c,29,8000,16000,32,8,16,132
5,1,470v/b,26,8000,32000,64,8,32,318
...,...,...,...,...,...,...,...,...,...
201,27,80/4,180,512,4000,0,1,3,14
202,27,80/5,180,262,4000,0,1,3,18
203,27,80/6,180,512,4000,0,1,3,21
204,27,80/8,124,1000,8000,0,1,8,42
205,27,90/80-model-3,98,1000,8000,32,2,8,46

### c.	Drop the column ‘model’.

In [15]:
df.drop(['model'],axis=1,inplace=True)

In [16]:
df

,vendor,cycle_time,min_memory,max_memory,cache,min_threads,max_threads,score
0,0,125,256,6000,256,16,128,198
1,1,29,8000,32000,32,8,32,269
2,1,29,8000,32000,32,8,32,220
3,1,29,8000,32000,32,8,32,172
4,1,29,8000,16000,32,8,16,132
...,...,...,...,...,...,...,...,...
204,27,124,1000,8000,0,1,8,42
205,27,98,1000,8000,32,2,8,46
206,28,125,2000,8000,0,2,14,52
207,29,480,512,8000,32,0,0,67
208,29,480,1000,4000,0,0,0,45

In [17]:
# Assuming your DataFrame is named 'cpu_data'

# Selecting 'score' as the target variable
target_variable = df['score']

# Selecting remaining columns as predictors
predictors = df.drop(['score'], axis=1)

In [19]:
predictors

,vendor,cycle_time,min_memory,max_memory,cache,min_threads,max_threads
0,0,125,256,6000,256,16,128
1,1,29,8000,32000,32,8,32
2,1,29,8000,32000,32,8,32
3,1,29,8000,32000,32,8,32
4,1,29,8000,16000,32,8,16
...,...,...,...,...,...,...,...
204,27,124,1000,8000,0,1,8
205,27,98,1000,8000,32,2,8
206,28,125,2000,8000,0,2,14
207,29,480,512,8000,32,0,0
208,29,480,1000,4000,0,0,0

### 4.	Split the data into training and testing data set in the ratio 80:20.

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(predictors, target_variable, test_size=0.2, random_state=42)

### 
5.	As part of model building, perform the following activities:
a.	Based on the training data, build a Linear Regression model.

In [24]:
from sklearn.linear_model import LinearRegression
# Building a Linear Regression model
linear_regression = LinearRegression()
linear_regression.fit(X_train, y_train)

LinearRegression()

### Finding the train and test scores for the model

In [25]:
train_score = linear_regression.score(X_train, y_train)
test_score = linear_regression.score(X_test, y_test)

### c.	Calculate the adjusted R-Squared values on both the train and the test data.

In [29]:
from sklearn.linear_model import LinearRegression
r_squared = linear_regression.score(X_train,y_train)
r_squared

0.8397245199815209

#### 7.	Based on the model built, predict the performance score of a new test sample/ new CPU instance which is given below:

In [35]:
new_instance = {
    'vendor' : 14 ,
    'model':'AM12',
    'cycle_time':300,
    'min_memory':630,
    'max_memory':6750,
    'cache':5,
    'min_threads':5,
    'max_threads':5
}
new_data = pd.DataFrame([new_instance])
new_data

,vendor,model,cycle_time,min_memory,max_memory,cache,min_threads,max_threads
0,14,AM12,300,630,6750,5,5,5

In [45]:
import pandas as pd

# Assuming you have a DataFrame 'cpu_data' and 'linear_regression' as your trained Linear Regression model

# New instance data
new_instance = {
    'vendor': 14,
    'model': 'AM12',
    'cycle_time': 300,
    'min_memory': 630,
    'max_memory': 6750,
    'cache': 5,
    'min_threads': 5,
    'max_threads': 5
}

# Create a DataFrame for the new instance
new_data = pd.DataFrame([new_instance])

# Ensure 'model' is not used in the prediction, assuming it's not used in the model
new_data

,vendor,model,cycle_time,min_memory,max_memory,cache,min_threads,max_threads
0,14,AM12,300,630,6750,5,5,5

In [50]:
import statsmodels.api as sm
new_data = sm.add_constant(new_data)

#view new DataFrame
print(new_data)

   cycle_time  min_memory  max_memory  cache  min_threads  max_threads  \
0         300         630        6750      5            5            5

   vendor_14
0       True

In [52]:
y = df['score']
x = df[['vendor', 'cycle_time','min_memory','max_memory','cache','min_threads','max_threads']]

In [53]:
x = sm.add_constant(x)

#fit linear regression model
model = sm.OLS(y, x).fit()

In [56]:
model.predict(x)

0      332.090780
1      307.096759
2      307.096759
3      307.096759
4      194.659406
          ...
204     25.031830
205     43.887667
206     49.550207
207     44.666752
208      9.631866
Length: 209, dtype: float64

#### 6.	Calculate the VIF values for all the features considered while building the model using the train data.

In [57]:
from sklearn.linear_model import LinearRegression
from statsmodels.stats.outliers_influence import variance_inflation_factor

# Assuming you have a DataFrame 'X_train' and 'y_train' for your training data

# Create a Linear Regression model and fit it to the training data
linear_regression = LinearRegression()
linear_regression.fit(X_train, y_train)

# Calculate VIF values for the features
vif = pd.DataFrame()
vif["Feature"] = X_train.columns
vif["VIF"] = [variance_inflation_factor(X_train.values, i) for i in range(X_train.shape[1])]

print(vif)

       Feature       VIF
0       vendor  2.378136
1   cycle_time  1.447409
2   min_memory  4.962445
3   max_memory  5.774714
4        cache  2.507915
5  min_threads  3.076406
6  max_threads  2.625980